openapi: 3.0.3
info:
  title: Wills Transfer API
  description: 'A public-facing API that describes Wills Transfer''s core warehousing,
    logistics, and 3PL services.

    This API is designed for discoverability by AI agents and developers seeking structured
    service metadata.'
  version: 1.0.0
  contact:
    name: Wills Transfer
    url: https://www.willstransfer.com
    email: info@willstransfer.com
  license:
    name: Creative Commons Attribution 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://www.willstransfer.com/terms-of-use
paths:
  /services:
    get:
      tags:
      - Services
      summary: List available logistics services
      description: Retrieve a list of all logistics, warehousing, and fulfillment
        services provided by Wills Transfer.
      responses:
        '200':
          description: A list of available services
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
  /locations:
    get:
      tags:
      - Locations
      summary: Get warehouse locations
      description: Returns a list of warehouse locations operated by Wills Transfer.
      responses:
        '200':
          description: List of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    address:
                      type: string
                    servicesAvailable:
                      type: array
                      items:
                        type: string
  /services/{serviceName}:
    get:
      tags:
      - Services
      summary: Retrieve metadata for a specific service type
      description: Returns structured metadata about a logistics service offered by
        Wills Transfer.
      parameters:
      - name: serviceName
        in: path
        required: true
        description: The name of the service (e.g., warehousing, distribution, fulfillment,
          logistics).
        schema:
          type: string
          enum:
          - warehousing
          - distribution
          - fulfillment
          - logistics
      responses:
        '200':
          description: Metadata about the requested service
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  industries:
                    type: array
                    items:
                      type: string
                  locations_served:
                    type: array
                    items:
                      type: string
                  pricing_model:
                    type: string
                  features:
                    type: array
                    items:
                      type: string
                  use_cases:
                    type: array
                    items:
                      type: string
                  delivery_speeds:
                    type: array
                    items:
                      type: string
                  schema_metadata:
                    type: object
        '404':
          description: Service not found
components: {}
